apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: developerteam1
  namespace: argocd
spec:
  description: 'Developer Team 1'
  destinations:
  - namespace: developerteam1-stage
    server: https://kubernetes.default.svc
  - namespace: developerteam1-prod
    server: https://kubernetes.default.svc
  roles:
  - description: 'Development Team 1 Admins'
    groups:
    - developerteam1
    name: developerteam1
    policies:
    - p, proj:developerteam1:developerteam1, applications, *, developerteam1/*, allow
  sourceRepos:
  - '*'