apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: developerteam1-stage

# namePrefix: alices-
# nameSuffix: -v2

# commonLabels:
#   someName: someValue

# commonAnnotations:
#   oncallPager: 800-555-1212

patchesStrategicMerge:
- replica-and-rollout-strategy.yaml

images:
- name: eu.gcr.io/kube-bootcamp-pc/basic-spring-boot
  newTag: 1.2.35

resources:
- ../../base
