apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: basic-spring-boot-git-first-run
  namespace: developerteam1-cicd
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  type: git
  params:
  - name: url
    value: git@github.com:paolocarta/spring-rest-tekton-pipeline.git
  - name: revision
    value: master