apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self-gitops
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: bootstrap
  source:
    path: 1.1-argocd-installation-manual-steps
    repoURL: https://github.com/paolocarta/kube-gitops-cicd-pipeline.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


