apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: gitops-manifests-pipe-resource
spec:
  type: git
  params:
  - name: url
    value: git@github.com:paolocarta/kube-gitops-cicd-pipeline.git
  - name: revision
    value: master