apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: {{ include "springboot-tekton.fullname" . }}-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/{{ include "springboot-tekton.fullname" . }}