apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: {{ include "springboot-tekton.fullname" . }}-image
spec:
  type: image
  params:
  - name: url
    value: eu.gcr.io/kube-bootcamp-pc/{{ include "springboot-tekton.fullname" . }}