apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: argocd-task-sync-and-wait
spec:
  params:
    - name: application-name
      description: name of the application to sync
    - name: revision
      description: the revision to sync to
      default: master
    - name: flags
      default: --
    - name: argocd-version
      default: v2.0.0
  stepTemplate:
    envFrom:
      - configMapRef:
          name: argocd-env-configmap  # used for server address
      # - secretRef:
      #     name: argocd-env-secret  # used for authentication 
  steps:
    - name: sync
      image: argoproj/argocd:$(params.argocd-version)
      script: |
        argocd app sync $(params.application-name) --revision $(params.revision) $(params.flags) --server $ARGOCD_SERVER --loglevel debug --insecure
        # argocd app sync $(params.application-name) --revision $(params.revision) $(params.flags) --server $ARGOCD_SERVER --loglevel debug --auth-token $ARGOCD_AUTH_TOKEN
    - name: wait
      image: argoproj/argocd:$(params.argocd-version)      
      script: |
        argocd app wait $(params.application-name) --health $(params.flags) --server $ARGOCD_SERVER --loglevel debug