apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
{{ include "springboot-tekton.labels" . | nindent 4 }}
  name: maven-and-image-build
spec:
  workspaces:
  - name: maven-repo
  - name: output-area
  params:
    - name: GOALS
      default:
        - package
        - -DskipTests
      description: The Maven goals to run
      type: array
    - name: kanikoImage
      description: "Kaniko image"
      type: string
      default: "gcr.io/kaniko-project/executor:v1.5.2@sha256:e61c08a27311884ff0d39a3ed4467f3c23444d73e03387fc9c7d5c6442796bae"
    - name: kanikoBuildArgs
      description: "Kaniko build arguments (default: none)"
      # type: array
      # default: []
      type: string
      default: ""
    - name: kanikoContextPath
      description: "Build context used by kaniko (default: ./, see https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)"
      type: string
      default: ./
      # default: $(resources.inputs.git.path) # if "workingDir" inside steps not specified
    - name: dockerfilePath
      description: "Path to the Dockerfile (default: ./Dockerfile)"
      type: string
      default: ./Dockerfile
      # default: $(resources.inputs.git.path)/Dockerfile # if "workingDir" inside steps not specified
    # if output resource not specified
    - name: imageRef
      description: "Reference (name) of the image to build"
      type: string
      default: eu.gcr.io/kube-bootcamp-pc/basic-spring-boot

  resources:
    inputs:
      - name: source
        type: git
    outputs:
      - name: image
        type: image

  steps:   
  - name: package
    image: {{ .Values.maven.image.repository }}:{{ .Values.maven.image.tag }}
    workingDir: /workspace/source
    command:
    - mvn
    args:
    - -Dmaven.repo.local=$(workspaces.maven-repo.path)
    - "$(inputs.params.GOALS)"

  - name: make-upload-dir
    image: quay.io/openshift-pipeline/openshift-cli:v0.8.0
    command: ["mkdir"]
    args:
      - -p
      - /workspace/source/upload

  - name: copy-assets 
    image: quay.io/openshift-pipeline/openshift-cli:v0.8.0
    command: ["cp"]
    args:
      - /workspace/source/target/shift-rest-1.0.0-SNAPSHOT.jar
      - /workspace/source/upload 

  - name: copy-assets-2
    image: quay.io/openshift-pipeline/openshift-cli:v0.8.0
    command: ["cp"]
    args:
      - /workspace/source/Dockerfile
      - /workspace/source/upload

  - name: new-version
    image: clamer/kikd:1.0.3
    imagePullPolicy: IfNotPresent
    workingDir: /workspace/source
    script: |
      cp -r /tekton/home/.ssh /root/.ssh
      jx-release-version
      VERSION=$(jx-release-version)
      git fetch --tags && jx-release-version > /workspace/output-area/version


  - name: tag-git-repo
    image: clamer/kikd:1.0.3
    imagePullPolicy: IfNotPresent
    workingDir: /workspace/source
    command: ["/bin/bash"]
    args:
      - -c
      - git tag $(cat /workspace/output-area/version)
     
  - name: build-and-push
    image: $(params.kanikoImage)
    workingDir: $(resources.inputs.source.path)
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /secret/kaniko-secret.json
    command:
      - /kaniko/executor
    args:
      - --dockerfile=$(params.dockerfilePath)
      - --context=$(params.kanikoContextPath)
        # - --destination=$(resources.outputs.image.url)
      - --destination=eu.gcr.io/kube-bootcamp-pc/basic-spring-boot:$(cat /workspace/output-area/version)
    volumeMounts:
      - name: gcr-creds
        mountPath: /secret

  - name: push-git-tag
    image: clamer/kikd:1.0.3
    imagePullPolicy: IfNotPresent
    workingDir: /workspace/source
    script: |
      # eval $(ssh-agent)
      # ssh-add /tekton/home/.ssh/id_*
      # git config --global user.email "tekton@tekton.dev"
      # git config --global user.name "Tekton Pipeline"
      cp -r /tekton/home/.ssh /root/.ssh
      git push origin --tags

  volumes:
{{- if .Values.sonar.enabled }}
  - name: "$(inputs.params.volumeName)"
    configMap:
      name: "$(inputs.params.CFGNAME)"
{{- end }}
    - name: gcr-creds
      secret:
        secretName: gcr-creds