apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: developerteam1-prod

patchesStrategicMerge:
- replica-and-rollout-strategy.yaml

images:
- name: image-registry.openshift-image-registry.svc:5000/developerteam1-cicd/basic-spring-boot
  newTag: 1.2.17

resources:
- ../../base
