apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-spring-boot
  # namespace: developerteam1-prod
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
