## CIOps role bindings
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline_edit-stage
  namespace: developerteam1-stage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: developerteam1-cicd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline_edit-prod
  namespace: developerteam1-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: developerteam1-cicd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline_edit-with-key-stage
  namespace: developerteam1-stage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: pipeline-with-keys
  namespace: developerteam1-cicd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline_edit-with-key-prod
  namespace: developerteam1-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: pipeline-with-keys
  namespace: developerteam1-cicd
## GitOps role bindings
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: system:image-puller-from-stage
#   namespace: developerteam1-cicd
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: system:image-puller
# subjects:
# - apiGroup: rbac.authorization.k8s.io
#   kind: Group
#   name: system:serviceaccounts:developerteam1-stage
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: system:image-puller-from-prod
#   namespace: developerteam1-cicd
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: system:image-puller
# subjects:
# - apiGroup: rbac.authorization.k8s.io
#   kind: Group
#   name: system:serviceaccounts:developerteam1-prod